// WARNING: this file was generated automatically by balde-template-gen

#ifndef __base_balde_template
#define __base_balde_template

#include <balde.h>

extern gchar* balde_str_template_base(balde_app_t *app, balde_request_t *request, balde_response_t *response);
extern void balde_template_base(balde_app_t *app, balde_request_t *request, balde_response_t *response);

#endif
